"""Helpers for publishing recommendations to Spotify."""

import spotipy


def create_recommendation_playlist(
    sp: spotipy.Spotify,
    track_uris: list[str],
    name: str = "Recommended Songs",
) -> str:
    """Create a private playlist in the current user's account and populate it."""
    playlist = sp._post(
        "me/playlists",
        payload={
            "name": name,
            "public": False,
            "description": "Top recommended tracks generated by the Spotify Recommender.",
        },
    )

    # Spotify renamed playlist track-management endpoints to /items for
    # Development Mode apps in 2026.
    sp._post(
        f"playlists/{playlist['id']}/items",
        payload={"uris": track_uris},
    )

    return playlist["external_urls"]["spotify"]
