import spotipy

def create_recommendation_playlist(sp: spotipy.Spotify, user_id: str, track_uris: list[str], name="Recommended Songs"):
    """
    Create a new playlist in the user's account and populate it with tracks.
    """
    print(f"[debug] Creating playlist for user {user_id}, {len(track_uris)} tracks")

    try:
        playlist = sp.user_playlist_create(
            user=user_id,
            name=name,
            public=False,
            description="Top recommended tracks generated by the Spotify Recommender."
        )
        print("[debug] Playlist created:", playlist["id"])
    except Exception as e:
        print("[debug] Failed during playlist create:", e)
        raise

    try:
        sp.user_playlist_add_tracks(user=user_id, playlist_id=playlist["id"], tracks=track_uris)
        print("[debug] Tracks added successfully")
    except Exception as e:
        print("[debug] Failed adding tracks:", e)
        raise

    return playlist["external_urls"]["spotify"]
