import spotipy
from spotipy.oauth2 import SpotifyOAuth

def create_recommendation_playlist(sp: spotipy.Spotify, user_id: str, track_uris: list[str], name="Recommended Songs"):
    """Create a new playlist in the user's account and populate it with tracks."""
    playlist = sp.user_playlist_create(
        user=user_id,
        name=name,
        public=False,
        description="Top recommended tracks generated by the Spotify Recommender."
    )
    playlist_id = playlist["id"]

    # Spotify lets up to 100 tracks per request
    sp.user_playlist_add_tracks(user=user_id, playlist_id=playlist_id, tracks=track_uris)
    return playlist["external_urls"]["spotify"]
